### ISSUE TITLE
mwdb.SECRET_KEY not found

### ISSUE THREAD

**Issue by vertebarbe** [CERT-Polska/karton-playground#12]
Hello, when trying the project I had this error:

![image](https://user-images.githubusercontent.com/35434346/173395019-c4d0ce59-5a95-4b93-bb54-95036463a152.png)

Everything works after adding MWDB_SECRET_KEY environment variable to docker-compose.yml.

![image](https://user-images.githubusercontent.com/35434346/173395331-5b2aab43-716c-4357-b74a-b80f2c917a8f.png)

Cheers,

**Comment by nazywam** [comment]
Could you share more information on your setup?
We're trying to recreate the issue but a fresh `docker compose up --build` works fine for us. 

Under normal circumstances the secret key should loaded from the config file: https://github.com/CERT-Polska/karton-playground/blob/master/config/mwdb.ini#L5

**Comment by vertebarbe** [comment]
For some reason I also can't reproduce the issue on a clean setup, so I don't know what happened here.

Thanks for the quick answer and these great projects!
